---
name: ISSUE_TRACKER
about: Tracking issues
<<<<<<< HEAD
title: "[DATE]: [FEATURE NAME]"
labels: tracking issue, needs triage, automated task
assignees: freightcorpbot
---
=======
title: '[DATE]: [FEATURE NAME]'
labels: tracking issue, needs triage, automated task
assignees: freightcorpbot
---

>>>>>>> bfffaef570885b39d6a7314eccb14f8e6c18ce71
