
contact_links:
  - name: Support request
    url: https://github.com/freight-trust/Support
    about: For Support, Please Visit the GitHub Directory for Support
    email: support@freight.zendesk.com