name: PR Changelog Addition
on:
  pull_request:
    types:
<<<<<<< HEAD
<<<<<<< HEAD
    - opened
    - edited
    - synchronized
    - labeled
    - unlabeled
=======
=======
>>>>>>> 2.0.0
      - opened
      - edited
      - synchronized
      - labeled
      - unlabeled
<<<<<<< HEAD
>>>>>>> bfffaef570885b39d6a7314eccb14f8e6c18ce71
=======
>>>>>>> 2.0.0
jobs:
  add_to_changelog:
    runs-on: ubuntu-latest
    steps:
<<<<<<< HEAD
<<<<<<< HEAD
    - uses: guzzler/file-changelog-issue-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
=======
      - uses: guzzler/file-changelog-issue-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
>>>>>>> bfffaef570885b39d6a7314eccb14f8e6c18ce71
=======
      - uses: guzzler/file-changelog-issue-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
>>>>>>> 2.0.0
